export const GET_POKEMONS_BEGIN = 'GET_POKEMONS_BEGIN';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR';
export const GET_SINGLE_POKEMON_BEGIN = 'GET_SINGLE_POKEMON_BEGIN';
export const GET_SINGLE_POKEMON_SUCCESS = 'GET_SINGLE_POKEMON_SUCCESS';
export const GET_SINGLE_POKEMON_ERROR = 'GET_SINGLE_POKEMON_ERROR';

export const SORT_POKEMONS = 'SORT_POKEMONS';
export const UPDATE_SORT = 'UPDATE_SORT';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
